import './globals.css';
import type { Metadata, Viewport } from 'next';

export const metadata: Metadata = {
  title: 'Carp Log',
  description: 'Track every fish, every trip — shared between you and the crew.',
  manifest: '/manifest.json',
  appleWebApp: {
    capable: true,
    statusBarStyle: 'black-translucent',
    title: 'Carp Log',
  },
  applicationName: 'Carp Log',
  formatDetection: { telephone: false },
  icons: {
    icon: [
      { url: '/icons/icon-192.png', sizes: '192x192', type: 'image/png' },
      { url: '/icons/icon-512.png', sizes: '512x512', type: 'image/png' },
    ],
    apple: [{ url: '/icons/apple-touch-icon.png', sizes: '180x180', type: 'image/png' }],
  },
};

export const viewport: Viewport = {
  themeColor: '#0A1816',
  width: 'device-width',
  initialScale: 1,
  maximumScale: 1,
  viewportFit: 'cover',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://unpkg.com/leaflet@1.9.4/dist/leaflet.css"
          integrity="sha256-p4NxAoJBhIIN+hmNHrzRCf9tD/miZyoHS5obTRR9BMY=" crossOrigin="" />
        <link rel="apple-touch-icon" href="/icons/apple-touch-icon.png" />
        <meta name="apple-mobile-web-app-capable" content="yes" />
        <meta name="apple-mobile-web-app-status-bar-style" content="black-translucent" />
        <meta name="apple-mobile-web-app-title" content="Carp Log" />
        {/* iOS splash screens (generated by scripts/gen-icons.mjs) */}
        <link rel="apple-touch-startup-image" media="(device-width: 390px) and (device-height: 844px)" href="/splash/iphone13.png" />
        <link rel="apple-touch-startup-image" media="(device-width: 428px) and (device-height: 926px)" href="/splash/iphone13promax.png" />
        <link rel="apple-touch-startup-image" media="(device-width: 375px) and (device-height: 812px)" href="/splash/iphonex.png" />
      </head>
      <body>{children}</body>
    </html>
  );
}
